DROP DATABASE IF EXISTS auth;

CREATE DATABASE IF NOT EXISTS auth;

USE auth;

CREATE TABLE user (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(70) NOT NULL UNIQUE,
    password VARCHAR(1000) NOT NULL
);
